// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package gen

type Tag struct {
	Text          string
	ID            int64
	UserID        int64
	TransactionID int64
}

type Transaction struct {
	Description string
	Currency    string
	ID          int64
	OwnerID     int64
	Amount      int64
	IsIncome    int64
	CreatedAt   int64
}

type User struct {
	PrimaryCurrency string
	Username        string
	Password        string
	Image           string
	ID              int64
	Balance         int64
}
